In [44]:
import numpy as np

In [117]:
arr1 = np.array([1, 2, 3, 4, 5])


In [126]:
print(arr1)

[[0 1]
 [2 3]
 [4 5]]


In [127]:
print("Shape of arr1:", arr1.shape)


Shape of arr1: (3, 2)


In [128]:
arr1 = np.array([(0, 1), (2, 3), (4,5)])


In [129]:
arr2 = arr1.reshape(2, 3)


In [130]:
print("Shape of arr2:", arr2.shape)

Shape of arr2: (2, 3)


In [131]:
arr3 = np.array([6, 7, 8, 9, 10])

print("Second array:")
print(arr3)

Second array:
[ 6  7  8  9 10]


In [135]:
a_1=np.array([6,7,8])
a_2=np.array([9,10])

In [133]:
result = np.concatenate((a_1, a_2))

print("Concatenated array:")
print(result)


Concatenated array:
[ 6  7  8  9 10]


In [134]:
mean_value = np.mean(result)
median_value = np.median(result)
std_dev = np.std(result)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_dev)

Mean: 8.0
Median: 8.0
Standard Deviation: 1.4142135623730951
